// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
 

import { initFormatters } from './formatters';
import type { Locales, Translations } from './i18n-types';
import { loadedFormatters, loadedLocales, locales } from './i18n-util';

import en from './en';
import en_us from './en-us';
import it from './it';
import pt_br from './pt-br';

const localeTranslations = {
	en,
	'en-us': en_us,
	it,
	'pt-br': pt_br
};

export const loadLocale = (locale: Locales): void => {
	if (loadedLocales[locale]) return;

	loadedLocales[locale] = localeTranslations[locale] as unknown as Translations;
	loadFormatters(locale);
};

export const loadAllLocales = (): void => locales.forEach(loadLocale);

export const loadFormatters = (locale: Locales): void =>
	void (loadedFormatters[locale] = initFormatters(locale));
