// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
 

import { initI18nSvelte } from 'typesafe-i18n/svelte';
import { loadedFormatters, loadedLocales } from './i18n-util';

const { locale, LL, setLocale } = initI18nSvelte(loadedLocales, loadedFormatters);

export { locale, LL, setLocale };

export default LL;
